# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      foreach($file in Get-ChildItem "*.lyrics")
      {
        echo $(webflow)
        $meta = (Get-Content $file)[0] -split " \| "
        $meta1 = $meta[0]
        $meta2 = $meta[1]
        Write-Host "##vso[task.setvariable variable=world;]$meta1"
        Write-Host "##vso[task.setvariable variable=story;]$meta2"

        $storyContent = Get-Content $file -Encoding utf8  | Select-Object -Skip 2
        echo $storyContent
        Write-Host "##vso[task.setvariable variable=content;]$storyContent" 
        Invoke-WebRequest -Uri "https://api.webflow.com/sites" -Headers "{'Authorization' = 'Bearer $(webflow)'}"
      }
