# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
    world: empty
    story: empty
    content: empty
pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      foreach($file in Get-ChildItem "*.lyrics")
      {
        $meta = (Get-Content $file)[0] -split " \| "
        Write-Host "##vso[task.setvariable variable=world;]$meta[0]"
        Write-Host "##vso[task.setvariable variable=story]$meta[1]"
        echo $(world)
        echo $(story)

        $storyContent = Get-Content $file -Encoding utf8  | Select-Object -Skip 2
        Write-Host "##vso[task.setvariable variable=content;]$storyContent" 
        echo $(content)
      }
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo $(WORLD)
