# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: traversemonde
    type: git
    name: traversemonde/traversemonde
    ref: main


steps:
  - checkout: self
      
  # Get template with pathtofile@repositoryname
  - template: update.yml@traversemonde

