# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      foreach($file in Get-ChildItem "*.lyrics")
      {
        $meta = (Get-Content $file)[0] -split " \| "
        $world = $meta[0]
        $story = $meta[1]

        $content = Get-Content $file -Encoding utf8  | Select-Object -Skip 2
        $collections = Invoke-RestMethod -Uri "https://api.webflow.com/sites/$(site)/collections" -Headers @{'Authorization' = 'Bearer $(webflow)'; 'accept-version' = '1.0.0'}
        $relatedCollection = $collections | Where-Object -Property singularName -Eq $world

        $collectionId = $relatedCollection._id
        $collectionItems = Invoke-RestMethod -Uri "https://api.webflow.com/collections/$collectionId/items" -Headers @{'Authorization' = 'Bearer $(webflow)'; 'accept-version' = '1.0.0'}

        $relatedItem = $collectionItems.items | Where-Object -Property name -Eq $story
        $relatedItemId = $relatedItem._id
        $storyContent = [String]::Join("`r`n",$content)

        $body = @{
            fields = @{
                name = $relatedItem.name
                slug = $relatedItem.slug
                _archived = $relatedItem._archived
                _draft = $relatedItem._draft
                story = $storyContent
            }
        }

        $jsonBody = $body | ConvertTo-Json

        $updateResponse = Invoke-RestMethod -Method Put -Uri "https://api.webflow.com/collections/$collectionId/items/$relatedItemId" -Body ([System.Text.Encoding]::UTF8.GetBytes($jsonBody)) -Headers @{'Authorization' = 'Bearer $(webflow)'; 'accept-version' = '1.0.0'; 'Content-Type' = 'application/json; charset=utf-8'}
    
      }
