# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      foreach($file in Get-ChildItem "*.lyrics")
      {
        $meta = (Get-Content $file)[0] -split " \| "
        ${env:WORLD} = $meta[0]
        ${env:STORY} = $meta[1]
        echo ${env:WORLD}
        echo ${env:STORY}

        ${env:CONTENT} = Get-Content $file -Encoding utf8  | Select-Object -Skip 2 
        echo ${env:CONTENT}
      }
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      $(WORLD)
